version: "2"

services:
  frontend:
    container_name: "redux-observable-starter"
    build: .
    environment:
      env_file: .env
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
